#spring.profiles.include: discovery,security

spring:
  #cloud.zookeeper:
  #  discovery.enabled: true
  #  enabled: true
  #  connectString: defaultZkHost:2181/${app.tenant}
  application.name: shopping-carts

#spring.data.mongodb:
#  host: defaultMongoServer

app:
  minPort: 8080
  maxPort: 8080
  tenant: a06-fr
  perimeter: trainingm-shopping