# spring.profiles.include: discovery,security

spring:
  application.name: products

app:
  minPort: 8080
  maxPort: 8080
  tenant: a06-fr
  perimeter: trainingm-order

spring.datasource:
  url: jdbc:h2:mem:testdb
  username: sa
  password:
  driverClassName: org.h2.Driver

eureka:
  client:
    service-url:
      default-zone: http://192.168.1.101:8761/eureka